---
zabbix_valid_server_versions:
  "15":
    - 6.4
    - 6.2
    - 6.0

pgsql_depenencies:
  "15":
    - gzip
    - python3-psycopg2

_zabbix_server_fping6location: null
_zabbix_server_fpinglocation: /usr/sbin/fping
