---
- name: restart php-fpm
  ansible.builtin.service:
    name: "{{ _php_fpm_service[ansible_facts['os_family']] | default('php-fpm') }}"
    state: restarted
    enabled: true
  become: true
  vars:
    _php_fpm_service:
      Debian: "php{{ zabbix_web_php_installed_version }}-fpm"

- name: test http service config
  listen: restart http service
  ansible.builtin.command:
    cmd: "{{ _cmd[zabbix_web_http_server] }}"
  become: true
  vars:
    _cmd:
      apache: "{{ _apache_test_cmd }}"
      nginx: nginx -t
  register: _test_http_service
  notify: restart tested http service config

- name: restart tested http service config
  when: _test_http_service.rc == 0
  ansible.builtin.service:
    name: "{{ zabbix_web_http_service }}"
    state: restarted
    enabled: true
  become: true
