---
- name: restart php-fpm
  ansible.builtin.service:
    name: "{{ _php_fpm_service[ansible_facts['os_family']] | default('php-fpm') }}"
    state: restarted
    enabled: true
  become: true
  vars:
    _php_fpm_service:
      Debian: "php{{ zabbix_web_php_installed_version }}-fpm"

- name: restart apache
  ansible.builtin.service:
    name: "{{ _apache_service }}"
    state: restarted
    enabled: true
  become: true

- name: test nginx config
  listen: restart nginx
  ansible.builtin.command: nginx -t
  register: zabbix_nginx_cfg_check
  notify: restart nginx tested
  become: true

- name: restart nginx tested
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  become: true
  when:
    - zabbix_nginx_cfg_check.rc == 0
