---
- name: "Apache | Install apache vhost"
  ansible.builtin.template:
    src: apache_vhost.conf.j2
    dest: "{{ zabbix_web_vhost_location }}"
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  vars:
    _document_root: "{{ zabbix_web_version is version('7.2', '>=') | ternary('/usr/share/zabbix/ui','/usr/share/zabbix') }}"
  when: zabbix_web_create_vhost
  become: true
  notify:
    - restart apache
  tags:
    - config

- name: "Apache | Enable Site (Debian Only)"
  ansible.builtin.file:
    src: "{{ zabbix_web_vhost_location }}"
    dest: /etc/apache2/sites-enabled/zabbix.conf
    state: link
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  become: true
  when: ansible_facts['os_family'] == 'Debian' and zabbix_web_create_vhost
  tags:
    - config
