---
- name: "Nginx | Determining Nginx version"
  when:
    - zabbix_web_create_vhost
    - zabbix_web_tls
  tags:
    - config
  block:
    - name: "Nginx | Gather package facts"
      ansible.builtin.package_facts:
        manager: auto
      become: true

    - name: "Nginx | Parse installed package version"
      ansible.builtin.set_fact:
        zabbix_web_nginx_installed_version: "{{ (ansible_facts.packages[item] | first).version | regex_search('\\d+\\.\\d+\\.\\d+') }}"
      loop:
        - nginx
        - nginx-core
        - nginx-full
        - nginx-light
      when:
        - item in ansible_facts.packages
        - zabbix_web_nginx_installed_version is not defined

- name: "Nginx | Install vhost in conf.d"
  ansible.builtin.template:
    src: nginx_vhost.conf.j2
    dest: "{{ zabbix_web_vhost_location }}"
    owner: root
    group: root
    mode: 0644
  vars:
    _document_root: "{{ zabbix_web_version is version('7.2', '>=') | ternary('/usr/share/zabbix/ui','/usr/share/zabbix') }}"
    _nginx_version: "{{ zabbix_web_nginx_installed_version | default('0.0.0') }}"
  when:
    - zabbix_web_create_vhost
  become: true
  notify:
    - restart nginx
  tags:
    - config

- name: Debian family symlinks
  when:
    - ansible_facts['os_family'] == 'Debian'
    - zabbix_web_create_vhost
  become: true
  tags:
    - config
  block:
    - name: Add symlinks
      when: item.is_required | default(true)
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: link
        src: "{{ item.src }}"
        owner: root
        group: root
      loop:
        - path: /etc/nginx/conf.d/zabbix.conf
          src: "{{ zabbix_web_vhost_location }}"
          is_required: "{{ zabbix_web_vhost_location != '/etc/nginx/conf.d/zabbix.conf' }}"
      loop_control:
        label: "{{ item.path }}"
      notify:
        - restart nginx
