---
- name: "Nginx | Install vhost in conf.d"
  ansible.builtin.template:
    src: nginx_vhost.conf.j2
    dest: "{{ zabbix_web_vhost_location }}"
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  when:
    - zabbix_web_create_vhost
  become: true
  notify:
    - restart nginx
  tags:
    - config
