---
- hosts: all

  vars:
    _version_groups: ["v60", "v70", "v72", "v74", "v80"]
    _g_to_v:
      v60: "6.0"
      v70: "7.0"
      v72: "7.2"
      v74: "7.4"
      v80: "8.0"

  pre_tasks:
    # The api is hosted in a container on the localhost, exposed to a known port,
    # that we delegate_to.
    # ansible_port is required to give each host a unique persistent connection;
    # without it, all localhost targets share one connection regardless of
    # zabbix_api_server_port.
    - name: Add zabbix web API hosts to inventory
      add_host:
        name: "zabbix-web-{{ _version }}"
        ansible_host: localhost
        ansible_port: "{{ 8000 + (_version | regex_replace('v', '') | int) }}"
        zabbix_api_server_port: "{{ 8000 + (_version | regex_replace('v', '') | int) }}"
      loop: "{{ groups.keys() | list | intersect(_version_groups) }}"
      loop_control:
        loop_var: _version
      changed_when: false # don't fail idempotency tests because of this.

  roles:
    - role: zabbix_proxy
