---
_zabbix_web_user:
  apache: www-data
  nginx: www-data
_zabbix_web_group:
  apache: www-data
  nginx: www-data
_zabbix_web_vhost_location:
  apache: /etc/zabbix/apache.conf
  nginx: /etc/zabbix/nginx.conf

_apache_log: apache2
_apache_service: apache2

_zabbix_web_create_php_fpm: "{{ zabbix_web_http_server != 'apache' }}"
_zabbix_php_fpm_dir: /etc/php/{{ zabbix_web_php_installed_version }}/fpm/pool.d
_zabbix_php_fpm_listen: /var/run/php/zabbix.sock
_zabbix_php_fpm_mode: "0660"
_zabbix_php_fpm_allowed_clients: 127.0.0.1
_zabbix_php_fpm_session: /var/lib/php/sessions/

_nginx_tls_crt: /etc/ssl/certs/ssl-cert-snakeoil.pem
_nginx_tls_key: /etc/ssl/private/ssl-cert-snakeoil.key
_nginx_tls_dhparam: /etc/ssl/private/dhparams.pem

_zabbix_web_package: zabbix-frontend-php
