---
_zabbix_web_user:
  apache: apache
  nginx: nginx
_zabbix_web_group:
  apache: apache
  nginx: nginx
_zabbix_web_vhost_location:
  apache: /etc/httpd/conf.d/zabbix.conf
  nginx: /etc/nginx/conf.d/zabbix.conf

_apache_log: httpd
_apache_service: httpd

_zabbix_php_fpm_dir: /etc/php-fpm.d
_zabbix_php_fpm_listen: /run/php-fpm/zabbix.sock
_zabbix_php_fpm_session: /var/lib/php/session

_zabbix_web_package: "zabbix-web-{{ zabbix_server_database }}-{{ zabbix_web_version }}.{{ zabbix_web_version_minor }}"
_zabbix_web_conf_package: "zabbix-{{ zabbix_web_http_server }}-conf-{{ zabbix_web_version }}.{{ zabbix_web_version_minor }}"

_zabbix_web_disable_repo:
  - epel
