---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"
  tags:
    - always

- name: Determine Latest Supported Zabbix Version
  when: zabbix_web_service_version is not defined
  ansible.builtin.set_fact:
    zabbix_web_service_version: "{{ _zabbix_web_service_valid_versions[_os_key] | default(['7.4']) | first }}"
  tags:
    - always

- name: Check that version is supported
  when: zabbix_web_service_version_check | bool
  ansible.builtin.assert:
    that:
      - (zabbix_web_service_version | string) in _zabbix_web_service_valid_versions[_os_key]
    fail_msg: Zabbix version {{ zabbix_web_service_version }} is not supported on {{ _os_key }}
  tags:
    - always

- name: Install Repository
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_repo
  vars:
    zabbix_repo_version: "{{ zabbix_web_service_version }}"
  when: zabbix_manage_repo | default(true)

- name: "Configure SELinux when enabled"
  ansible.builtin.include_tasks: selinux.yml
  when: ansible_facts.selinux.status | default('disabled') == 'enabled'

- name: Install zabbix-web-service packages
  become: true
  ansible.builtin.package:
    name: "{{ zabbix_web_service_packages }}"
    state: "{{ zabbix_web_service_package_state }}"
    update_cache: true
    disablerepo: "{{ zabbix_web_service_disable_repo | default(_zabbix_web_service_disable_repo | default(omit)) }}"
    install_recommends: "{{ zabbix_web_service_install_recommends | default(_zabbix_web_service_install_recommends | default(omit)) }}"
  environment:
    http_proxy: "{{ zabbix_http_proxy | default('') }}"
    https_proxy: "{{ zabbix_https_proxy | default('') }}"
  register: _zabbix_web_service_package_installed
  until: _zabbix_web_service_package_installed is success
  tags:
    - install

- name: Google-chrome requirement - Create Zabbix directory structure with proper permissions
  become: true
  ansible.builtin.file:
    path: "{{ mimeapps_list_path }}"
    state: directory
    owner: "{{ zabbix_os_user }}"
    group: "{{ zabbix_os_user }}"
    mode: '0755'
    recurse: true
  notify:
    - zabbix-web-service restarted
  changed_when: false

- name: Google-chrome requirement - Create mimeapps.list file
  become: true
  ansible.builtin.command:
    cmd: "touch {{ mimeapps_list_path }}/mimeapps.list"
    creates: "{{ mimeapps_list_path }}/mimeapps.list"
  notify:
    - zabbix-web-service restarted

- name: Google-chrome requirement - Set mimeapps.list attributes
  become: true
  ansible.builtin.file:
    path: "{{ mimeapps_list_path }}/mimeapps.list"
    state: file
    owner: "{{ zabbix_os_user }}"
    group: "{{ zabbix_os_user }}"
    mode: '0644'
  notify:
    - zabbix-web-service restarted

- name: "Configure zabbix-web-service"
  become: true
  ansible.builtin.template:
    src: zabbix_web_service.conf.j2
    dest: "{{ zabbix_web_service_config }}"
    owner: "{{ zabbix_os_user }}"
    group: "{{ zabbix_os_user }}"
    mode: "{{ zabbix_web_service_conf_mode }}"
  notify:
    - zabbix-web-service restarted
  tags:
    - config

- name: "Zabbix-web-service started"
  become: true
  ansible.builtin.service:
    name: zabbix-web-service
    state: "{{ zabbix_service_state }}"
    enabled: "{{ zabbix_service_enabled }}"
  tags:
    - service
  when: zabbix_web_service_manage_service | bool

- name: Setting up the Frontend URL
  become: false
  run_once: true
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: "{{ zabbix_api_use_ssl }}"
    # --- Basic Auth (Begin) ---
    http_login_user: "{{ zabbix_api_http_user | default(-42) }}"
    http_login_password: "{{ zabbix_api_http_password | default(-42) }}"
    # --- Basic Auth (End) ---
    ansible_user: "{{ zabbix_api_login_user }}"
    ansible_httpapi_pass: "{{ zabbix_api_login_pass }}"
    ansible_httpapi_port: "{{ zabbix_api_server_port }}"
    ansible_httpapi_validate_certs: "{{ zabbix_api_validate_certs }}"
  community.zabbix.zabbix_settings:
    frontend_url: "{{ zabbix_frontend_url }}"
  when:
    - zabbix_api_frontend_url | bool
  delegate_to: "{{ zabbix_api_server_host }}"
  tags:
    - api
