---
# TODO: Update or remove in 6.0.0
- name: Deprecation /etc/zabbix/zabbix_server.conf.d
  block:
    - name: Check for deprecated zabbix_server.conf.d
      stat:
        path: "/etc/zabbix/zabbix_server.conf.d"
      register: _server_conf_d
    - name: Verify zabbix_server.conf.d is removed or explicitly specified
      assert:
        that:
          - not _server_conf_d.stat.exists or
            zabbix_server_include_dir == '/etc/zabbix/zabbix_server.conf.d'
        fail_msg: Old (deprecated) existing configuration
  rescue:
    - name: Deprecation notice for zabbix_server.conf.d
      debug:
        msg: "{{ deprecation_notice.split('\n') }}"
      vars:
        deprecation_notice: |
          [DEPRECATION] You should either manually set 'zabbix_server_include_dir' with existing legacy path, OR move
          files from '/etc/zabbix/zabbix_server.conf.d' to '{{ zabbix_server_include_dir }}', update 'Include=' in
          'zabbix_server.conf', and remove the old '/etc/zabbix/zabbix_server.conf.d' directory.
    - name: Provide deprecation override for zabbix_server_include_dir
      set_fact:
        zabbix_server_include_dir: "/etc/zabbix/zabbix_server.conf.d"
