---
- name: "SELinux | Install epel-release"
  ansible.builtin.package:
    name: epel-release
  environment:
    http_proxy: "{{ zabbix_http_proxy | default('') }}"
    https_proxy: "{{ zabbix_https_proxy | default('') }}"
  register: _zabbix_server_dependencies_installed
  until: _zabbix_server_dependencies_installed is succeeded
  become: true
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] is version('10', '>=')
  tags:
    - install

- name: "SELinux | Install related SELinux packages"
  ansible.builtin.package:
    name: "{{ _packages | select }}"
  vars:
    _is_ge_el10: "{{ ansible_facts['os_family'] == 'RedHat' and
      ansible_facts['distribution_major_version'] is version('10', '>=') }}"
    _packages:
      - "{{ (_is_ge_el10) | ternary('selinux-policy-epel', '') }}"
      - python3-libsemanage
      - python3-policycoreutils
      - zabbix-selinux-policy
  environment:
    http_proxy: "{{ zabbix_http_proxy | default('') }}"
    https_proxy: "{{ zabbix_https_proxy | default('') }}"
  register: _zabbix_server_dependencies_installed
  until: _zabbix_server_dependencies_installed is succeeded
  become: true
  tags:
    - install

- name: "SELinux | Set booleans"
  ansible.posix.seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: true
  become: true
  tags:
    - config
  loop:
    - name: zabbix_can_network
      state: "{{ selinux_allow_zabbix_can_network }}"
