---
zabbix_valid_web_service_versions:
  # Debian
  "12":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
  "11":
    - 6.0
  # Ubuntu
  "24":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
  "22":
    - 7.4
    - 7.2
    - 7.0
    - 6.0

_zabbix_web_service_packages:
  - "zabbix-web-service"
_zabbix_web_service_install_recommends: true
