---
- name: Prepare
  hosts: all

  pre_tasks:
    # issues on redhat with curl, so install curl-minimal.
    # suse containers have a partial python3.11 install, py311-rpm needed for ansible.builtin.package_facts
    - name: "Installing packages"
      ansible.builtin.package:
        name: "{{ _packages | select | list }}"
        update_cache: "{{ (ansible_facts['os_family'] in ['Debian', 'Suse']) | ternary(true, omit) }}"
      vars:
        _py3_rpm: "python3{% if ansible_facts.python.version.minor != 6 %}{{ ansible_facts.python.version.minor }}{% endif %}-rpm"
        _packages:
          - "curl{% if ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] | int > 8 %}-minimal{% endif %}"
          - "{{ (ansible_facts['os_family'] == 'Suse') | ternary(_py3_rpm, '') }}"
          - sudo
      register: installation_dependencies
      until: installation_dependencies is succeeded

    - name: "Configure SUDO."
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "Defaults    !requiretty"
        state: present

    - name: Enabling PHP 8.0
      ansible.builtin.dnf:
        name: "@php:8.0/common"
      when:
        - ansible_facts['os_family'] == 'RedHat'
        - ansible_facts['distribution_major_version'] == "8"

  tasks:
    - name: Install prerequisite packages for zabbix_web role
      package:
        name: "{{ _zabbix_web_prerequisite_packages[zabbix_web_http_server][ansible_facts.os_family] + _zabbix_web_php_deps[ansible_facts.os_family] | default([]) }}"
      vars:
        _suse_php_v: "{{ zabbix_web_version is version('7.0', '>=') | ternary('8', '7') }}"
        _suse_php_json: "{{ (_suse_php_v == '7') | ternary(['php7-json'], []) }}"  # php7-json is built-in on php8. Returns list for concatenation with _php_common.
        _suse_php_common: ["php{{ _suse_php_v }}-mysql", "php{{ _suse_php_v }}-openssl", "php{{ _suse_php_v }}-pgsql", "php{{ _suse_php_v }}-xmlreader", "php{{ _suse_php_v }}-xmlwriter"]
        _zabbix_web_prerequisite_packages:
          apache:
            Debian: ["apache2", "php-cli"]
            RedHat: ["httpd", "php-cli", "php-fpm"]
            Suse: ["apache2", "php{{ _suse_php_v }}-cli"]
          nginx:
            Debian: ["nginx", "php-fpm"]
            RedHat: ["nginx", "php-cli", "php-fpm"]
            Suse: ["nginx", "php{{ _suse_php_v }}-cli", "php{{ _suse_php_v }}-fpm"]
        _zabbix_web_php_deps:  # php packages that aren't necessarily installed with the the main ones
          Debian: ["php-mysql", "php-pgsql"]
          Suse: "{{ _suse_php_json + _suse_php_common }}"

    - name: Debian | Enable apache modules
      when:
        - ansible_facts.os_family == "Debian"
        - zabbix_web_http_server == "apache"
      community.general.apache2_module:
        state: present
        name: "{{ item }}"
      loop:
        - rewrite
        - ssl
      notify: restart apache

    - name: Suse | Enable apache modules
      when:
        - ansible_facts.os_family == "Suse"
        - zabbix_web_http_server == "apache"
      lineinfile:
        path: /etc/sysconfig/apache2
        # Negative lookahead so we won't match on line that already contains option
        regexp: "^APACHE_MODULES=\"((?!.*\\b{{ item }}\\b).*)\"$"
        backrefs: true
        line: "APACHE_MODULES=\"\\1 {{ item }}\""
      loop:
        - rewrite
        - ssl
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

  post_tasks:
    - name: "Remove file"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/index.html
