---
- name: Prepare
  hosts: all

  pre_tasks:
    # issues on redhat with curl, so install curl-minimal.
    - name: "Installing packages"
      ansible.builtin.package:
        name:
          - "curl{% if ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] | int > 8 %}-minimal{% endif %}"
          - sudo
        update_cache: "{{ (ansible_facts['os_family'] in ['Debian', 'Suse']) | ternary(true, omit) }}"
      register: installation_dependencies
      until: installation_dependencies is succeeded

    - name: "Configure SUDO."
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "Defaults    !requiretty"
        state: present

    - name: Enabling PHP 8.0
      ansible.builtin.dnf:
        name: "@php:8.0/common"
      when:
        - ansible_facts['os_family'] == 'RedHat'
        - ansible_facts['distribution_major_version'] == "8"

  tasks:
    - name: Install prerequisite packages for zabbix_web role
      package:
        name: "{{ _zabbix_web_prerequisite_packages[zabbix_web_http_server][ansible_facts.os_family] }}"
      vars:
        _zabbix_web_prerequisite_packages:
          apache:
            Debian: ["apache2", "php-cli", "php-mysql", "php-pgsql"]
            RedHat: ["httpd", "php-cli", "php-fpm"]
            Suse: ["apache2", "php8-cli", "php8-mysql", "php8-openssl", "php8-pgsql", "php8-xmlreader", "php8-xmlwriter"]
          nginx:
            Debian: ["nginx", "php-fpm", "php-mysql", "php-pgsql"]
            RedHat: ["nginx", "php-cli", "php-fpm"]
            Suse: ["nginx", "php8-cli", "php8-fpm", "php8-mysql", "php8-openssl", "php8-pgsql", "php8-xmlreader", "php8-xmlwriter"]

    - name: Debian | Enable apache modules
      when:
        - ansible_facts.os_family == "Debian"
        - zabbix_web_http_server == "apache"
      community.general.apache2_module:
        state: present
        name: "{{ item }}"
      loop:
        - rewrite
        - ssl
      notify: restart apache

    - name: Suse | Enable apache modules
      when:
        - ansible_facts.os_family == "Suse"
        - zabbix_web_http_server == "apache"
      lineinfile:
        path: /etc/sysconfig/apache2
        # Negative lookahead so we won't match on line that already contains option
        regexp: "^APACHE_MODULES=\"((?!.*\\b{{ item }}\\b).*)\"$"
        backrefs: true
        line: "APACHE_MODULES=\"\\1 {{ item }}\""
      loop:
        - rewrite
        - ssl
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

  post_tasks:
    - name: "Remove file"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/index.html
