---
name: "community.zabbix.build_collection"
on:
  workflow_call:
jobs:
  build-collection:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: molecule/requirements.txt

      - name: Install latest pip
        run: python -m pip install --upgrade pip yq

      - name: Install dependencies
        run: pip install -r molecule/requirements.txt

      - name: Build the collection
        run: |
          # Pin versions to speed up CI
          sed -i 's/ansible\.windows:\s*"\*"/ansible.windows: "2.8.0"/' galaxy.yml
          sed -i 's/ansible\.netcommon:\s*"\*"/ansible.netcommon: "7.2.0"/' galaxy.yml
          sed -i 's/ansible\.posix:\s*"\*"/ansible.posix: "2.0.0"/' galaxy.yml
          sed -i 's/community\.general:\s*"\*"/community.general: "10.5.0"/' galaxy.yml
          sed -i 's/community\.mysql:\s*"\*"/community.mysql: "3.13.0"/' galaxy.yml
          sed -i 's/community\.postgresql:\s*"\*"/community.postgresql: "3.12.0"/' galaxy.yml
          echo '  geerlingguy.apache: "4.2.0"' >> galaxy.yml
          echo '  geerlingguy.nginx: "3.3.0"' >> galaxy.yml
          echo '  geerlingguy.php: "6.0.0"' >> galaxy.yml
          ansible-galaxy collection build -f

      - name: Upload collection artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-collection
          path: community-zabbix-*.tar.gz
